-- Generated from data/db.json by scripts/export-seed-sql.mjs
-- Content seed: run after 0001_init.sql, then manage via the admin UI.

insert into public.exercises (id, title, category, attribute, measurement, rep_style, progressions) values
  ('wrist-prep', 'Wrist Circles & Prep', 'both', 'warmup', 'reps', 'standard', '[{"id":"wrist-prep-p0","name":"Basic circles","order":0,"description":"Slow circles both directions, then palm lifts on the floor."},{"id":"wrist-prep-p1","name":"Loaded rocks","order":1,"description":"Rock weight over the hands in quadruped to load the wrists gently."},{"id":"wrist-prep-p2","name":"Fingertip work","order":2,"description":"Fingertip push-up holds to build resilient wrists and fingers."}]'::jsonb),
  ('band-dislocates', 'Band Shoulder Dislocates', 'both', 'warmup', 'reps', 'standard', '[{"id":"band-dislocates-p0","name":"Wide grip","order":0,"description":"Hands far apart; easy pass-overs to open the shoulders."},{"id":"band-dislocates-p1","name":"Medium grip","order":1,"description":"Narrow the grip as mobility improves; keep arms straight."},{"id":"band-dislocates-p2","name":"Narrow grip","order":2,"description":"Close grip pass-overs — significant shoulder mobility."}]'::jsonb),
  ('scap-pulls', 'Scapula Pulls', 'pull', 'warmup', 'reps', 'standard', '[{"id":"scap-pulls-p0","name":"Two-arm","order":0,"description":"From a dead hang, depress and retract the shoulder blades without bending the elbows."},{"id":"scap-pulls-p1","name":"Slow tempo","order":1,"description":"3–5s up and down per rep for control under load."},{"id":"scap-pulls-p2","name":"One-arm assisted","order":2,"description":"Shift weight to one arm; the other hand assists lightly."}]'::jsonb),
  ('scap-pushups', 'Scapula Push-ups', 'push', 'warmup', 'reps', 'standard', '[{"id":"scap-pushups-p0","name":"On knees","order":0,"description":"Protract and retract the shoulder blades in a kneeling plank."},{"id":"scap-pushups-p1","name":"Full plank","order":1,"description":"Same movement in a full plank; elbows stay locked."},{"id":"scap-pushups-p2","name":"Ring plank","order":2,"description":"On rings — instability makes the serratus work overtime."}]'::jsonb),
  ('jumping-jacks', 'Jumping Jacks', 'both', 'warmup', 'reps', 'standard', '[{"id":"jumping-jacks-p0","name":"Standard","order":0,"description":"Two minutes easy pace to raise the pulse."},{"id":"jumping-jacks-p1","name":"Fast pace","order":1,"description":"Short fast bursts to finish the general warm-up."}]'::jsonb),
  ('front-lever', 'Front Lever', 'pull', 'skill', 'time', 'standard', '[{"id":"front-lever-p0","name":"Tuck","order":0,"description":"Knees pulled to the chest, hips at bar height, arms straight. Build to 20s."},{"id":"front-lever-p1","name":"Advanced tuck","order":1,"description":"Open the hip angle to ~90°; keep the back flat."},{"id":"front-lever-p2","name":"Single leg","order":2,"description":"One leg extended fully, the other tucked; swap sides evenly."},{"id":"front-lever-p3","name":"Straddle","order":3,"description":"Both legs extended wide; squeeze toward full over time."},{"id":"front-lever-p4","name":"Full","order":4,"description":"Body fully horizontal under the bar with straight arms."}]'::jsonb),
  ('back-lever', 'Back Lever', 'both', 'skill', 'time', 'standard', '[{"id":"back-lever-p0","name":"German hang","order":0,"description":"Skin-the-cat to a relaxed hang behind the body; builds shoulder extension."},{"id":"back-lever-p1","name":"Tuck","order":1,"description":"Knees tucked, facing the floor; find the balance point."},{"id":"back-lever-p2","name":"Advanced tuck","order":2,"description":"Hips open to ~90°, back flat, arms locked."},{"id":"back-lever-p3","name":"Straddle","order":3,"description":"Legs wide and extended; brace hard through the glutes."},{"id":"back-lever-p4","name":"Full","order":4,"description":"Fully horizontal facing down, arms straight behind you."}]'::jsonb),
  ('handstand', 'Handstand', 'push', 'skill', 'time', 'standard', '[{"id":"handstand-p0","name":"Wall plank","order":0,"description":"Feet on a box or low wall walk-ups; stack shoulders over hands."},{"id":"handstand-p1","name":"Chest-to-wall hold","order":1,"description":"Nose to the wall, hollow body, push tall through the shoulders."},{"id":"handstand-p2","name":"Back-to-wall hold","order":2,"description":"Kick up with heels resting on the wall; practice taking heels off."},{"id":"handstand-p3","name":"Freestanding","order":3,"description":"Balance without support; fingertip corrections, 30s+ goal."}]'::jsonb),
  ('l-sit', 'L-sit', 'both', 'skill', 'time', 'standard', '[{"id":"l-sit-p0","name":"Foot-supported","order":0,"description":"Hands on floor or parallettes, heels lightly supported."},{"id":"l-sit-p1","name":"Tuck","order":1,"description":"Knees to chest, feet off the floor, shoulders depressed."},{"id":"l-sit-p2","name":"One leg","order":2,"description":"Extend one leg at a time; keep both hips level."},{"id":"l-sit-p3","name":"Full L-sit","order":3,"description":"Both legs horizontal, knees locked, toes pointed."}]'::jsonb),
  ('planche', 'Planche', 'push', 'skill', 'time', 'standard', '[{"id":"planche-p0","name":"Planche lean","order":0,"description":"Plank with shoulders pushed far past the wrists; straight arms."},{"id":"planche-p1","name":"Tuck","order":1,"description":"Knees tucked tight, feet off the floor, full protraction."},{"id":"planche-p2","name":"Advanced tuck","order":2,"description":"Flatten the back and open the hips to ~90°."},{"id":"planche-p3","name":"Straddle","order":3,"description":"Legs wide and extended behind you; elite strength required."}]'::jsonb),
  ('pull-up', 'Pull-up', 'pull', 'strength', 'reps', 'standard', '[{"id":"pull-up-p0","name":"Band-assisted","order":0,"description":"A band under the feet reduces bodyweight; full range every rep."},{"id":"pull-up-p1","name":"Negatives","order":1,"description":"Jump to the top, lower under control in 3–5s."},{"id":"pull-up-p2","name":"Full pull-up","order":2,"description":"Dead hang to chin over the bar, no kipping."},{"id":"pull-up-p3","name":"Chest-to-bar","order":3,"description":"Pull higher until the chest touches; builds lever strength."},{"id":"pull-up-p4","name":"Weighted","order":4,"description":"Add load with a belt or vest; progress in small jumps."}]'::jsonb),
  ('dip', 'Dip', 'push', 'strength', 'reps', 'standard', '[{"id":"dip-p0","name":"Support hold","order":0,"description":"Lock out on bars or rings and simply hold; 30s target."},{"id":"dip-p1","name":"Negatives","order":1,"description":"Lower from support to full depth in 3–5s."},{"id":"dip-p2","name":"Full dip","order":2,"description":"Full range: shoulder below elbow at the bottom, lockout at top."},{"id":"dip-p3","name":"Ring dip","order":3,"description":"The instability of rings roughly doubles the difficulty."},{"id":"dip-p4","name":"Weighted","order":4,"description":"Add external load once 10+ clean ring dips are easy."}]'::jsonb),
  ('push-up', 'Push-up', 'push', 'strength', 'reps', 'standard', '[{"id":"push-up-p0","name":"Incline","order":0,"description":"Hands elevated on a box or bar; easier angle."},{"id":"push-up-p1","name":"Full push-up","order":1,"description":"Chest to the floor, body in one line."},{"id":"push-up-p2","name":"Diamond","order":2,"description":"Hands together under the chest; triceps-heavy."},{"id":"push-up-p3","name":"Pseudo planche","order":3,"description":"Hands turned back beside the hips, shoulders leaned far forward."}]'::jsonb),
  ('row', 'Bodyweight Row', 'pull', 'strength', 'reps', 'standard', '[{"id":"row-p0","name":"Incline row","order":0,"description":"Body at a steep angle under a high bar or rings."},{"id":"row-p1","name":"Horizontal row","order":1,"description":"Body horizontal under a low bar; chest to the bar."},{"id":"row-p2","name":"Archer row","order":2,"description":"One arm does most of the work, the other stays straight."},{"id":"row-p3","name":"One-arm row","order":3,"description":"Full single-arm row on a ring; anti-rotation core work."}]'::jsonb),
  ('pike-press', 'Pike Push-up / HSPU', 'push', 'strength', 'reps', 'standard', '[{"id":"pike-press-p0","name":"Pike push-up","order":0,"description":"Hips high, head toward the floor between the hands."},{"id":"pike-press-p1","name":"Elevated pike push-up","order":1,"description":"Feet on a box to shift more weight onto the shoulders."},{"id":"pike-press-p2","name":"Wall HSPU","order":2,"description":"Handstand push-up with heels on the wall; full range with blocks."},{"id":"pike-press-p3","name":"Freestanding HSPU","order":3,"description":"Handstand push-up in balance — the end boss of pressing."}]'::jsonb),
  ('muscle-up', 'Muscle-up', 'both', 'strength', 'reps', 'standard', '[{"id":"muscle-up-p0","name":"High pull-up","order":0,"description":"Pull explosively to the sternum or lower chest."},{"id":"muscle-up-p1","name":"Explosive chest-to-bar","order":1,"description":"Add speed; think about pulling the bar to the hips."},{"id":"muscle-up-p2","name":"Band-assisted MU","order":2,"description":"A band helps through the transition over the bar."},{"id":"muscle-up-p3","name":"Strict MU","order":3,"description":"No kip: pull, transition, and press in one controlled motion."}]'::jsonb),
  ('squat', 'Squat', 'legs', 'strength', 'reps', 'standard', '[{"id":"squat-p0","name":"Air squat","order":0,"description":"Full-depth bodyweight squat, heels down."},{"id":"squat-p1","name":"Split squat","order":1,"description":"Rear foot elevated; single-leg emphasis."},{"id":"squat-p2","name":"Shrimp squat","order":2,"description":"Rear foot held in hand behind you; knee taps the floor."},{"id":"squat-p3","name":"Pistol squat","order":3,"description":"Full single-leg squat, free leg extended forward."}]'::jsonb),
  ('nordic-curl', 'Nordic Curl', 'legs', 'strength', 'reps', 'cluster', '[{"id":"nordic-curl-p0","name":"Band-assisted","order":0,"description":"A band from above takes some load through the hardest range."},{"id":"nordic-curl-p1","name":"Negatives","order":1,"description":"Lower as slowly as possible; push back up with hands."},{"id":"nordic-curl-p2","name":"Full nordic","order":2,"description":"Full curl up from the floor using hamstrings only."}]'::jsonb),
  ('hip-thrust', 'Glute Bridge / Hip Thrust', 'legs', 'strength', 'reps', 'standard', '[{"id":"hip-thrust-p0","name":"Glute bridge","order":0,"description":"Shoulders on the floor, drive the hips up and squeeze."},{"id":"hip-thrust-p1","name":"Single-leg bridge","order":1,"description":"One leg extended; hips stay square."},{"id":"hip-thrust-p2","name":"Hip thrust","order":2,"description":"Shoulders elevated on a bench for a longer range."},{"id":"hip-thrust-p3","name":"Weighted hip thrust","order":3,"description":"Load across the hips; the strongest glute builder."}]'::jsonb),
  ('leg-raise', 'Hanging Leg Raise', 'both', 'strength', 'reps', 'standard', '[{"id":"leg-raise-p0","name":"Knee raise","order":0,"description":"Hanging, pull the knees to the chest without swinging."},{"id":"leg-raise-p1","name":"L raise","order":1,"description":"Straight legs to horizontal; compress hard."},{"id":"leg-raise-p2","name":"Toes-to-bar","order":2,"description":"Straight legs all the way to the bar, controlled down."}]'::jsonb),
  ('burpees', 'Burpees', 'both', 'cardio', 'reps', 'standard', '[{"id":"burpees-p0","name":"Step-back","order":0,"description":"Step (don''t jump) in and out of the plank; low impact."},{"id":"burpees-p1","name":"Standard","order":1,"description":"Jump back, push-up, jump forward, jump up."},{"id":"burpees-p2","name":"Chest-to-floor","order":2,"description":"Full chest contact each rep; highest intensity."}]'::jsonb),
  ('jump-rope', 'Jump Rope', 'legs', 'cardio', 'time', 'standard', '[{"id":"jump-rope-p0","name":"Single unders","order":0,"description":"Steady rhythm, soft knees, tall posture."},{"id":"jump-rope-p1","name":"High pace","order":1,"description":"Intervals: 40s fast / 20s easy."},{"id":"jump-rope-p2","name":"Double unders","order":2,"description":"Two rope passes per jump; wrists do the work."}]'::jsonb),
  ('cuban-rotation', 'Cuban Rotation', 'pull', 'prehabilitation', 'reps', 'standard', '[{"id":"cuban-rotation-p0","name":"Band","order":0,"description":"Row, rotate up, press — all against light band tension."},{"id":"cuban-rotation-p1","name":"Light dumbbell","order":1,"description":"Same pattern with light dumbbells; strict and slow."}]'::jsonb),
  ('band-pullapart', 'Band Pull-apart', 'pull', 'prehabilitation', 'reps', 'standard', '[{"id":"band-pullapart-p0","name":"Standard","order":0,"description":"Arms straight, pull the band to the chest, pinch the blades."},{"id":"band-pullapart-p1","name":"Overhead","order":1,"description":"Pull the band apart overhead; keep the ribs down."}]'::jsonb),
  ('wrist-curls', 'Wrist Curls', 'both', 'prehabilitation', 'reps', 'standard', '[{"id":"wrist-curls-p0","name":"Bodyweight","order":0,"description":"Kneeling wrist rocks and lifts in all directions."},{"id":"wrist-curls-p1","name":"Light load","order":1,"description":"Wrist curls and extensions with a light dumbbell."},{"id":"wrist-curls-p2","name":"Rice bucket","order":2,"description":"Grip, rotate and dig in a rice bucket for forearm health."}]'::jsonb),
  ('ext-rotation', 'External Rotation', 'both', 'prehabilitation', 'reps', 'standard', '[{"id":"ext-rotation-p0","name":"Band at side","order":0,"description":"Elbow pinned to the ribs; rotate the forearm outward."},{"id":"ext-rotation-p1","name":"Band at 90°","order":1,"description":"Upper arm horizontal; rotate up against the band."}]'::jsonb),
  ('ring-curl', 'Ring Bicep Curl', 'pull', 'isolation', 'reps', 'standard', '[{"id":"ring-curl-p0","name":"High incline","order":0,"description":"Body at a steep angle; curl the rings to the forehead."},{"id":"ring-curl-p1","name":"Horizontal","order":1,"description":"Body closer to horizontal for more load."},{"id":"ring-curl-p2","name":"Feet elevated","order":2,"description":"Feet up — maximum bodyweight through the biceps."}]'::jsonb),
  ('ring-extension', 'Ring Tricep Extension', 'push', 'isolation', 'reps', 'standard', '[{"id":"ring-extension-p0","name":"High incline","order":0,"description":"Bodyweight skull-crusher at an easy angle."},{"id":"ring-extension-p1","name":"Horizontal","order":1,"description":"Lower the ring height to increase the lever."},{"id":"ring-extension-p2","name":"Feet elevated","order":2,"description":"Hardest angle; keep the elbows tracking straight."}]'::jsonb),
  ('face-pull', 'Face Pull', 'pull', 'isolation', 'reps', 'standard', '[{"id":"face-pull-p0","name":"Band","order":0,"description":"Pull the band to the face, elbows high, external rotation at the end."},{"id":"face-pull-p1","name":"Rings","order":1,"description":"Bodyweight face pull leaning back under rings."}]'::jsonb),
  ('pancake', 'Pancake Stretch', 'legs', 'flexibility', 'time', 'standard', '[{"id":"pancake-p0","name":"Supported","order":0,"description":"Sit on a cushion, legs wide, fold with a flat back."},{"id":"pancake-p1","name":"Full fold","order":1,"description":"Chest toward the floor between wide legs."},{"id":"pancake-p2","name":"Weighted","order":2,"description":"Light plate held at the chest to deepen the fold."}]'::jsonb),
  ('shoulder-ext', 'Shoulder Extension Stretch', 'both', 'flexibility', 'time', 'standard', '[{"id":"shoulder-ext-p0","name":"Floor","order":0,"description":"Hands behind you on the floor, fingers back; slide the hips forward."},{"id":"shoulder-ext-p1","name":"Elevated","order":1,"description":"Hands on a bench behind you; sink the shoulders."},{"id":"shoulder-ext-p2","name":"German hang","order":2,"description":"Full hang behind the body on rings or bar; breathe."}]'::jsonb),
  ('thoracic-bridge', 'Thoracic Bridge', 'both', 'flexibility', 'time', 'standard', '[{"id":"thoracic-bridge-p0","name":"Table bridge","order":0,"description":"Hips up, chest open, gaze back — gentle opener."},{"id":"thoracic-bridge-p1","name":"Full bridge","order":1,"description":"Push to a full bridge; straighten the arms."},{"id":"thoracic-bridge-p2","name":"Elevated bridge","order":2,"description":"Feet elevated to bias the upper back and shoulders."}]'::jsonb),
  ('hang-decompress', 'Hanging Decompression', 'both', 'cooldown', 'time', 'standard', '[{"id":"hang-decompress-p0","name":"Feet supported","order":0,"description":"Passive hang with feet lightly on the floor."},{"id":"hang-decompress-p1","name":"Full hang","order":1,"description":"Relaxed dead hang; let the spine and shoulders lengthen."}]'::jsonb),
  ('breathing', 'Down-regulation Breathing', 'both', 'cooldown', 'time', 'standard', '[{"id":"breathing-p0","name":"4-4-8 pattern","order":0,"description":"Inhale 4s, hold 4s, exhale 8s — five rounds lying down."},{"id":"breathing-p1","name":"Box breathing","order":1,"description":"4s each: in, hold, out, hold."}]'::jsonb)
on conflict (id) do nothing;

insert into public.techniques (id, name, description) values
  ('tech-harder-progression', 'Harder progression step', 'Move to the next progression of the exercise once you own the current one (e.g. tuck → advanced tuck).'),
  ('tech-tempo', 'Slower tempo / pauses', 'Same exercise, but slow the eccentric or add pauses to make each rep harder.'),
  ('tech-leverage', 'Leverage change', 'Increase the lever: elevate feet, widen the straddle less, or move rings further apart.')
on conflict (id) do nothing;

insert into public.default_template (id, entries) values ('default', '[{"exerciseId":"wrist-prep","progressionId":"wrist-prep-p0","sets":[{"reps":10}],"restSeconds":30},{"exerciseId":"band-dislocates","progressionId":"band-dislocates-p0","sets":[{"reps":10}],"restSeconds":30},{"exerciseId":"scap-pulls","progressionId":"scap-pulls-p0","sets":[{"reps":8},{"reps":8}],"restSeconds":60},{"exerciseId":"front-lever","progressionId":"front-lever-p0","sets":[{"reps":5},{"reps":5},{"reps":5}],"restSeconds":180},{"exerciseId":"cuban-rotation","progressionId":"cuban-rotation-p0","sets":[{"reps":12},{"reps":12}],"restSeconds":60},{"exerciseId":"ring-curl","progressionId":"ring-curl-p0","sets":[{"reps":10},{"reps":10}],"restSeconds":90},{"exerciseId":"shoulder-ext","progressionId":"shoulder-ext-p0","sets":[{"reps":5}],"restSeconds":30},{"exerciseId":"hang-decompress","progressionId":"hang-decompress-p0","sets":[{"reps":1}],"restSeconds":0}]'::jsonb)
on conflict (id) do update set entries = excluded.entries;
